const { contextBridge, ipcRenderer } = require('electron')

contextBridge.exposeInMainWorld('gitTool', {
  selectRepo: () => ipcRenderer.invoke('dialog:selectRepo'),
  selectFiles: (opts) => ipcRenderer.invoke('dialog:selectFiles', opts),
  selectDir: (opts) => ipcRenderer.invoke('dialog:selectDir', opts),
  refresh: (repoPath) => ipcRenderer.invoke('git:refresh', { repoPath }),
  diff: (repoPath, file, cached) => ipcRenderer.invoke('git:diff', { repoPath, file, cached }),
  add: (repoPath, files) => ipcRenderer.invoke('git:add', { repoPath, files }),
  addAll: (repoPath) => ipcRenderer.invoke('git:addAll', { repoPath }),
  reset: (repoPath, files) => ipcRenderer.invoke('git:reset', { repoPath, files }),
  resetAll: (repoPath) => ipcRenderer.invoke('git:resetAll', { repoPath }),
  commit: (repoPath, message) => ipcRenderer.invoke('git:commit', { repoPath, message }),
  push: (repoPath) => ipcRenderer.invoke('git:push', { repoPath }),
  getUser: (repoPath, scope) => ipcRenderer.invoke('git:getUser', { repoPath, scope }),
  setUser: (repoPath, name, email, scope) => ipcRenderer.invoke('git:setUser', { repoPath, name, email, scope }),
  initRepo: (dirPath) => ipcRenderer.invoke('git:init', { dirPath }),
  cloneRepo: (url, parentDir) => ipcRenderer.invoke('git:clone', { url, parentDir }),
  getRemote: (repoPath) => ipcRenderer.invoke('git:getRemote', { repoPath }),
  setRemote: (repoPath, url) => ipcRenderer.invoke('git:setRemote', { repoPath, url }),
  removeRemote: (repoPath) => ipcRenderer.invoke('git:removeRemote', { repoPath }),
  listBranches: (repoPath) => ipcRenderer.invoke('git:listBranches', { repoPath }),
  checkout: (repoPath, branch) => ipcRenderer.invoke('git:checkout', { repoPath, branch }),
  checkoutRemote: (repoPath, remoteBranch, localName) => ipcRenderer.invoke('git:checkoutRemote', { repoPath, remoteBranch, localName }),
  createBranch: (repoPath, branchName, baseBranch) => ipcRenderer.invoke('git:createBranch', { repoPath, branchName, baseBranch }),
  mergePull: (repoPath, op, source, target) => ipcRenderer.invoke('git:mergePull', { repoPath, op, source, target }),
  log: (repoPath) => ipcRenderer.invoke('git:log', { repoPath }),
  listCommits: (repoPath) => ipcRenderer.invoke('git:listCommits', { repoPath }),
  resetToCommit: (repoPath, commitHash, mode) => ipcRenderer.invoke('git:resetToCommit', { repoPath, commitHash, mode }),
  addExternal: (repoPath, filePaths, destDir, allowOverwrite) =>
    ipcRenderer.invoke('git:addExternal', { repoPath, filePaths, destDir, allowOverwrite }),
  readFile: (repoPath, file) => ipcRenderer.invoke('git:readFile', { repoPath, file }),
  writeFile: (repoPath, file, content) => ipcRenderer.invoke('git:writeFile', { repoPath, file, content }),
  getAppInfo: () => ipcRenderer.invoke('app:getInfo'),
  detectGit: () => ipcRenderer.invoke('git:detectGit'),
  getGitInfo: () => ipcRenderer.invoke('git:getGitInfo'),
  setGitPath: (gitPath) => ipcRenderer.invoke('git:setGitPath', { gitPath }),
  openExternal: (url) => ipcRenderer.invoke('app:openExternal', url),
})
